version: '2'
services:
  bot:
    build: .
    command: nodemon libotrio.js
    volumes:
      - .:/code
    environment:
      - SLACK_ACCESS_TOKEN
      - SLACK_WEBHOOK_URL
      - JENKINS_USER
      - JENKINS_API_TOKEN
      - LIBOTRIO_DEPLOY_TRIGGER_URL
      - MONGODB_URI
      - ATLASSIAN_USER
      - ATLASSIAN_PASS
      - GOOGLE_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
