version: '2'
services:
  bot:
    build: .
    volumes:
      - .:/code
    environment:
      - JIRA_API_CREDENTIALS
      - JIRA_HOST
      - SLACK_ACCESS_TOKEN
      - SLACK_CLIENTID
      - SLACK_CLIENTSECRET
      - SLACK_WEBHOOK_URL
      - JENKINS_USER
      - JENKINS_API_TOKEN
      - LIBOTRIO_DEPLOY_TRIGGER_URL
      - MONGODB_URI
      - ATLASSIAN_USER
      - ATLASSIAN_PASS
      - GOOGLE_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
