version: '2'
services:
  bot:
    ports:
      - "3000:3000"
      - "9229:9229"
    build: .
    volumes:
      - .:/code
    environment:
      - SLACK_ACCESS_TOKEN
      - SLACK_CLIENTID
      - SLACK_CLIENTSECRET
      - SLACK_WEBHOOK_URL
      - JENKINS_USER
      - JENKINS_API_TOKEN
      - LIBOTRIO_DEPLOY_TRIGGER_URL
      - MONGODB_URI
      - ATLASSIAN_USER
      - ATLASSIAN_PASS
      - GOOGLE_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
